PATH_BIN       = '/vhub/bin'
PATH_RUN       = '/vhub/run'
PATH_VAR       = '/vhub/var'
PATH_MNT       = '/vhub/mnt'
PATH_CONF      = '/vhub/conf'
PATH_INIT      = '/vhub/init'
PATH_LXC_LIB   = '/var/lib/lxc'
PATH_LXC_ROOT  = '/var/cache/lxc/precise/rootfs-i386'
