DEPS = []
PLAT = ['Linux']
INCL = ['src/vres/log']
INFO = {'name': '', 'version': '0.0.1'}
LIBS = ['pthread', 'rt', 'fuse', 'hiredis']
DEFS = ['_GNU_SOURCE', '_FILE_OFFSET_BITS=64']
ARGS = {
    'veth': {'type': 'bool'},
    'node': {'type': 'bool'},
    'debug': {'type': 'bool'},
    'error': {'type': 'bool'},
    'warning': {'type': 'bool'},
    'unshare': {'type': 'bool'},
    'log2file': {'type': 'bool'},
    'evaluate': {'type': 'bool'},
    'show_io': {'type': 'bool'},
    'show_mig': {'type': 'bool'},
    'show_shm': {'type': 'bool'},
    'show_sem': {'type': 'bool'},
    'show_msg': {'type': 'bool'},
    'show_tsk': {'type': 'bool'},
    'show_ipc': {'type': 'bool'},
    'show_rpc': {'type': 'bool'},
    'show_dmgr': {'type': 'bool'},
    'show_file': {'type': 'bool'},
    'show_node': {'type': 'bool'},
    'show_more': {'type': 'bool'},
    'show_dump': {'type': 'bool'},
    'show_klnk': {'type': 'bool'},
    'show_sync': {'type': 'bool'},
    'show_ckpt': {'type': 'bool'},
    'show_proc': {'type': 'bool'},
    'show_page': {'type': 'bool'},
    'show_line': {'type': 'bool'},
    'show_lock': {'type': 'bool'},
    'show_redo': {'type': 'bool'},
    'show_prio': {'type': 'bool'},
    'show_event': {'type': 'bool'},
    'trace_proc': {'type': 'bool'},
    'show_member': {'type': 'bool'},
    'show_record': {'type': 'bool'},
    'show_rwlock': {'type': 'bool'},
    'show_restore': {'type': 'bool'},
    'show_request': {'type': 'bool'},
    'show_barrier': {'type': 'bool'},
    'show_resource': {'type': 'bool'},
    'show_metadata': {'type': 'bool'},
    'ifname': {'type': 'str', 'default': 'eth0'},
    'manager_type': {'type': 'int', 'default': '0'},
    'mds_port': {'type': 'int', 'default': '23001'},
    'klnk_port': {'type': 'int', 'default': '12000'},
    'path_log': {'type': 'str', 'default': '/vhub/var/log'},
    'path_lbfs': {'type': 'str', 'default': '/vhub/mnt/lbfs'},
    'path_dump': {'type': 'str', 'default': '/vhub/init/dump'},
    'path_conf': {'type': 'str', 'default': '/vhub/conf/klnk'},
    'path_cache': {'type': 'str', 'default': '/vhub/var/cache'}
}
